# Generated by Django 6.0.7 on 2026-07-29 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jssg", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="vite_modules",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
