# Generated by Django 6.1 on 2026-08-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jssg", "0002_page_vite_modules"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="css",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
