[project]
name = "jssg"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = ["django>=6.0.7", "python-frontmatter>=1.3.0"]
license = "AGPL-3.0-only"

[project.scripts]
jssg = "jssg.manage:main"

[build-system]
requires = ["uv_build<0.12"]
build-backend = "uv_build"
