# Generated by Django 5.0.6 on 2024-05-11 18:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PageHit",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("timestamp_start", models.DateTimeField()),
                ("timestamp_end", models.DateTimeField()),
                ("duration", models.FloatField()),
                ("remote_address", models.GenericIPAddressField()),
                ("version", models.CharField(max_length=32)),
                ("method", models.CharField(max_length=32)),
                ("url", models.URLField(max_length=1024)),
                ("app_name", models.CharField(max_length=32)),
                ("view_name", models.CharField(max_length=128)),
                ("route", models.URLField()),
                ("user_agent", models.TextField()),
                ("accepted_types", models.TextField()),
                ("accepted_language", models.TextField()),
                ("accepted_encoding", models.TextField()),
                ("status", models.PositiveIntegerField(default=200)),
                ("content_type", models.TextField()),
                ("dnt", models.BooleanField(default=False)),
            ],
        ),
    ]
