# jssg - jtremesay's static site generator
# Copyright (C) 2026 Jonathan Tremesaygues
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""
Django settings for jssg project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import importlib.util
from os import environ
from pathlib import Path
from types import ModuleType

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path.cwd().resolve()


def load_website_settings(path: Path) -> ModuleType:
    """Load the JSSG website settings module from the given path."""
    spec = importlib.util.spec_from_file_location("jssg_settings", path)
    if spec is None or spec.loader is None:
        raise ImportError(f"Could not load settings module from {path}")

    jssg_settings = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(jssg_settings)

    return jssg_settings


# JSSG
JSSG_WEBSITE_DIR = Path(
    environ.get("JSSG_WEBSITE_DIR", (BASE_DIR / "website").resolve())
)
JSSG_SETTINGS = load_website_settings(JSSG_WEBSITE_DIR / "settings.py")

try:
    JSSG_SITE_NAME = environ["JSSG_SITE_NAME"]
except KeyError:
    try:
        JSSG_SITE_NAME = JSSG_SETTINGS.SITE_NAME
    except AttributeError:
        JSSG_SITE_NAME = "jtremesay.org"


JSSG_PAGES_DIR = JSSG_WEBSITE_DIR / "pages"
JSSG_STATIC_DIR = JSSG_WEBSITE_DIR / "static"
JSSG_TEMPLATES_DIR = JSSG_WEBSITE_DIR / "templates"
JSSG_DIST_DIR = JSSG_WEBSITE_DIR / "dist"
JSSG_REPO = "https://github.com/jtremesay/jtremesay.org"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-wap*-t2awv)5p(qhw0fnu1*xib^%imhjnuc%!)il3rdr#2(ek*"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["jtremesay.org", "localhost"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "jssg",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "jssg.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [JSSG_TEMPLATES_DIR],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "jssg.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "fr-fr"
TIME_ZONE = "Europe/Paris"
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [JSSG_STATIC_DIR]
STATIC_ROOT = JSSG_DIST_DIR / "static"
